### ISSUE TITLE
feature: try to detect language from filename for syntax highlighting

### ISSUE THREAD

**Issue by miketheman** [pypi/inspector#39]
Source: https://github.com/pypi/inspector/blob/1ef5cdac3baf7e3ce189bc876a62bcee2c807538/inspector/templates/code.html#L8-L9

When viewing a non-python file via Inspector, like a README.md, the browser highlights the contents incorrectly.

Prism supports a [lot of languages](https://prismjs.com/#supported-languages) and advises on using their [autoloader for languages](https://prismjs.com/#basic-usage-cdn).

**Comment by saip007** [comment]
hi @di, Can I work on the issue?
I have tested the changes locally, Should I need to add all languages or only a few

**Comment by di** [comment]
Sure! Seems like we should support all languages that Prism supports, via the autoloader.

**Comment by saip007** [comment]
Should I use the CDNs provided from PrismJS

**Comment by di** [comment]
I don't think so, we should include it here as a static file similar to: https://github.com/pypi/inspector/tree/main/inspector/static

**Comment by saip007** [comment]
Okay
