### ISSUE TITLE
Cert error while trying to access https://inspector.pypi.io/

### ISSUE THREAD

**Issue by rakovskij-stanislav** [pypi/inspector#41]
Problem: Current certificate on inspector.pypi.io is invalid. This site uses HSTS this way you cannot bypass an exception in chrome / edge / firefox without disabling HSTS, but it is very insecure.

Firefox:
```
Websites prove their identity via certificates. Firefox does not trust this site because it uses a
certificate that is not valid for inspector.pypi.io. The certificate is only valid for the following
names: *.ingress.cmh1.psfhosted.org, test.pypi.org, upload.pypi.org, *.cmh1.psfhosted.com,
*.pyfound.org, *.ingress.cmh1.psfhosted.com, *.cmh1.psfhosted.org
 ```

**Comment by ewdurbin** [comment]
This is resolved. The necessary SAN on the certificate was dropped unexpectedly when the cert auto renewed, but is now restored and a monitor has been setup for the endpoint.
