### ISSUE TITLE
Code that requires horizontal scrolling can easily be missed.

### ISSUE THREAD

**Issue by calebbrown** [pypi/inspector#48]
I encountered this package that appeared like this in my browser:
![package-no-wrap](https://user-images.githubusercontent.com/56095/183404201-d7f2f809-21d2-4a91-aeee-94f200f12a3a.png)
Being MacOS there was no horizontal scrollbar indicating there was text further to the right.

I added `white-space: pre-wrap` to the code block and this is what I found:
![package-wrapping-on](https://user-images.githubusercontent.com/56095/183404204-17aaa76e-95ad-425e-bfe1-180a8b25d71a.png)

This solution messes with the line numbers, but it made it obvious where the malicious code was.

**Comment by calebbrown** [comment]
The problem may actually be the `overflow: auto` on the `pre[class*=language-]` selector

**Comment by di** [comment]
The line in question is here: https://inspector.pypi.io/project/pyslyte/1.0.3/packages/b5/ea/595c6e0ab1b5f4d2b7f7d173b62e14c7cf3d058061a5fb31a265b9bfb2da/pyslyte-1.0.3.tar.gz/pyslyte-1.0.3/src/pyslyte/__init__.py#line.367

**Comment by di** [comment]
Another example of this: https://inspector.pypi.io/project/future-tasks/2.3/packages/13/86/06c7d3f48784152c0e04615d123456a7b85e090498dc7941c921efda2d66/future_tasks-2.3-py3-none-any.whl/future_tasks/__init__.py#line.112

**Comment by di** [comment]
Fixed in https://github.com/pypi/inspector/pull/60.
