### ISSUE TITLE
Error loading whl packages' contents

### ISSUE THREAD

**Issue by hx601939710** [pypi/inspector#54]
When processing the content of whl packages(zipfiles) of a project, all files show content as "None"

**Comment by di** [comment]
Can you give an example?

**Comment by hx601939710** [comment]
https://inspector.pypi.io/project/requests/2.28.1/packages/ca/91/6d9b8ccacd0412c08820f72cebaa4f0c0441b5cda699c90f618b6f8a1b42/requests-2.28.1-py3-none-any.whl/requests-2.28.1.dist-info/top_level.txt

I chose a random one, this file contains "requests" when I download the file from pypi.
