### ISSUE TITLE
Handle binary files, etc.

### ISSUE THREAD

**Issue by di** [pypi/inspector#6]
We should do something other than 500-error for things like https://inspector.pypi.io/project/tensorflow/2.9.1/packages/51/86/f5db15a6403a8ecf377807e93cdcd5cddb2f57e73604143cc02917d24db4/tensorflow-2.9.1-cp310-cp310-macosx_10_14_x86_64.whl/tensorflow/libtensorflow_framework.2.9.1.dylib

**Comment by Wouterkoorn** [comment]
To quickly (but temporarily) solve this, I would do the same as the "Distribution type not supported" message. Something like this:
```py 
class TarGzDistribution(Distribution):
    def contents(self, filepath: str) -> str | None:
        if file := self.tarfile.extractfile(filepath):
            return file.read().decode()

@app.route("/project/<project_name>/<version>/packages/<first>/<second>/<rest>/<distname>/<path:filepath>")
def get_file_display(project_name,version, first, second, rest, distname, filepath):
    if dist := _get_dist(first, second, rest, distname):
        if contents := dist.contents(filepath):
            return render_template(
                "code.html",
                code=contents,
                h2=f"{project_name}=={version}",
                h3=distname,
                h4=filepath,
            )
        return "Binary files are not supported"
    return "Distribution type not supported"
```
Unless you'd rather instantly go for a pretty solution with HTML

**Comment by di** [comment]
Doesn't need to be pretty, but I realized that some of these are just directories that we need to filter, e.g. 

https://inspector.pypi.io/project/tensorflow/2.9.1/packages/51/86/f5db15a6403a8ecf377807e93cdcd5cddb2f57e73604143cc02917d24db4/tensorflow-2.9.1-cp310-cp310-macosx_10_14_x86_64.whl/tensorflow/
