### ISSUE TITLE
Support disassembling `.pyc` files

### ISSUE THREAD

**Issue by di** [pypi/inspector#98]
We've seen some instances of malware being hidden in `.pyc` files (example [here](https://inspector.pypi.io/project/fshec2/1.0.0/packages/f6/c0/991b655e1362a05884cfb0e2b240102b83809633408684c304cafc29f4b6/fshec2-1.0.0-py3-none-any.whl/)) Currently this tool refuses to display `.pyc` files because they are binary. Instead, we should attempt to disassemble the bytecode to some degree and display as much as possible in the UI.

**Comment by AngeloD2022** [comment]
This is a fantastic idea. How should the UX be for this?
